// src/lib/styles.js
// Oggetto S con gli stili in linea condivisi da page.js e dalle tab.
// (Il CSS globale con classi e variabili resta in page.js.)

export const S = {
  root: { fontFamily:"'DM Sans',sans-serif", background:"var(--bg)", minHeight:"100vh", display:"flex", flexDirection:"column", position:"relative", overflow:"hidden", color:"var(--text)" },
  bgNoise: { position:"fixed", inset:0, backgroundImage:`url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.03'/%3E%3C/svg%3E")`, pointerEvents:"none", zIndex:0, opacity:0.4 },
  bgA1: { position:"fixed", top:-80, right:-80, width:360, height:360, borderRadius:"50%", background:"radial-gradient(circle,rgba(232,53,74,0.06) 0%,transparent 70%)", pointerEvents:"none", zIndex:0 },
  bgA2: { position:"fixed", bottom:-100, left:-60, width:400, height:400, borderRadius:"50%", background:"radial-gradient(circle,rgba(43,181,174,0.06) 0%,transparent 70%)", pointerEvents:"none", zIndex:0 },
  drawerOverlay: { position:"fixed", inset:0, background:"rgba(0,0,0,0.22)", backdropFilter:"blur(4px)", zIndex:1000, display:"flex", justifyContent:"flex-end" },
  drawer: { width:420, maxWidth:"92vw", background:"var(--surface)", height:"100%", display:"flex", flexDirection:"column", boxShadow:"-8px 0 40px rgba(0,0,0,0.12)", animation:"slideInRight 0.3s cubic-bezier(0.22,1,0.36,1)" },
  drawerHeader: { padding:"22px 24px 18px", borderBottom:"1px solid var(--border)", display:"flex", justifyContent:"space-between", alignItems:"center" },
  drawerTitle: { fontFamily:"'Playfair Display',serif", fontSize:18, fontWeight:900, color:"var(--text)" },
  drawerEmpty: { flex:1, display:"flex", flexDirection:"column", alignItems:"center", justifyContent:"center", padding:40, textAlign:"center" },
  drawerList: { flex:1, overflowY:"auto", padding:"16px 20px", display:"flex", flexDirection:"column", gap:14 },
  drawerItem: { background:"var(--surface2)", border:"1px solid var(--border)", borderRadius:12, padding:"14px 16px", display:"flex", flexDirection:"column", gap:10 },
  drawerItemMeta: { display:"flex", gap:6, alignItems:"center" },
  drawerItemText: { fontFamily:"'DM Sans',sans-serif", fontSize:12, color:"var(--text2)", lineHeight:1.7, whiteSpace:"pre-wrap", maxHeight:110, overflow:"hidden", WebkitMaskImage:"linear-gradient(to bottom,black 60%,transparent 100%)" },
  header: { borderBottom:"1px solid var(--border)", background:"var(--glass)", backdropFilter:"blur(20px)", position:"relative", zIndex:10 },
  headerInner: { maxWidth:900, margin:"0 auto", padding:"12px 20px", display:"flex", alignItems:"center", justifyContent:"space-between", flexWrap:"wrap", gap:10 },
  logo: { display:"flex", alignItems:"center", gap:14, flexShrink:0 },
  logoIconWrap: { width:40, height:40, background:"linear-gradient(135deg,#E8354A,#2BB5AE)", borderRadius:12, display:"flex", alignItems:"center", justifyContent:"center", animation:"floatSymbol 3s ease-in-out infinite" },
  logoMain: { fontFamily:"'Playfair Display',serif", fontSize:22, fontWeight:900, background:"linear-gradient(135deg,#E8354A 0%,#7B4FA0 60%,#2BB5AE 100%)", backgroundSize:"200% auto", WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent", animation:"gradientShift 4s ease infinite", letterSpacing:"-0.02em" },
  logoSub: { fontFamily:"'DM Sans',sans-serif", fontSize:10, color:"#aaa", letterSpacing:"0.18em", textTransform:"uppercase", marginTop:1 },
  clearBtn: { background:"transparent", border:"1px solid var(--border)", color:"#888", fontFamily:"'DM Sans',sans-serif", fontSize:12, fontWeight:500, padding:"6px 14px", borderRadius:20, letterSpacing:"0.04em", flexShrink:0, whiteSpace:"nowrap" },
  briefPanel: { borderBottom:"1px solid var(--border)", background:"var(--glass)", backdropFilter:"blur(20px)", position:"relative", zIndex:9, animation:"slideDown 0.25s cubic-bezier(0.22,1,0.36,1)", boxShadow:"0 8px 32px rgba(0,0,0,0.06)" },
  briefInner: { maxWidth:900, margin:"0 auto", padding:"26px 28px 20px", display:"flex", flexDirection:"column", gap:18 },
  briefTitle: { fontFamily:"'Playfair Display',serif", fontSize:18, fontWeight:700, color:"var(--text)" },
  briefSubtitle: { fontFamily:"'DM Sans',sans-serif", fontSize:11, color:"#999", letterSpacing:"0.06em", marginTop:3 },
  briefSection: { display:"flex", flexDirection:"column", gap:9 },
  briefLabel: { fontFamily:"'DM Sans',sans-serif", fontSize:10, color:"#bbb", letterSpacing:"0.14em", textTransform:"uppercase", fontWeight:600 },
  toneChip: { padding:"6px 16px", fontSize:12, fontWeight:500, border:"1.5px solid var(--border)", background:"transparent", color:"#888", borderRadius:20, fontFamily:"'DM Sans',sans-serif" },
  toneChipActive: { background:"rgba(232,53,74,0.08)", borderColor:"#E8354A", color:"#E8354A" },
  briefInput: { background:"var(--surface2)", border:"1.5px solid var(--border)", borderRadius:10, padding:"10px 14px", fontSize:13, fontFamily:"'DM Sans',sans-serif", color:"var(--text2)", width:"100%", lineHeight:1.7, outline:"none", transition:"all 0.2s ease" },
  saveBtn: { background:"linear-gradient(135deg,#E8354A,#7B4FA0)", border:"none", color:"#fff", fontFamily:"'DM Sans',sans-serif", fontWeight:600, fontSize:13, padding:"10px 26px", borderRadius:20, letterSpacing:"0.02em" },
  modeBar: { display:"flex", borderBottom:"1px solid var(--border)", background:"var(--glass2)", position:"relative", zIndex:10, overflowX:"auto" },
  modeBtn: { flex:"1 0 auto", minWidth:130, padding:"13px 18px", background:"transparent", border:"none", borderBottom:"3px solid transparent", display:"flex", flexDirection:"column", gap:3, color:"#bbb", fontFamily:"'DM Sans',sans-serif" },
  modeBtnLabel: { fontSize:12, fontWeight:700 },
  modeBtnDesc: { fontSize:9.5, opacity:0.6, letterSpacing:"0.03em" },
  platformBar: { display:"flex", alignItems:"center", gap:8, padding:"9px 28px", borderBottom:"1px solid var(--border)", background:"var(--glass)", position:"relative", zIndex:10, overflowX:"auto" },
  platformBtn: { padding:"5px 18px", fontSize:12, fontWeight:500, border:"1.5px solid var(--border)", background:"transparent", color:"#999", borderRadius:20, fontFamily:"'DM Sans',sans-serif", flexShrink:0 },
  ctxChip: { padding:"5px 14px", fontSize:11, fontWeight:500, border:"1.5px solid var(--border)", background:"transparent", color:"#aaa", borderRadius:20, fontFamily:"'DM Sans',sans-serif", flexShrink:0, whiteSpace:"nowrap" },
  chat: { flex:1, overflowY:"auto", padding:"36px 28px 120px", maxWidth:900, width:"100%", margin:"0 auto", display:"flex", flexDirection:"column", gap:24, position:"relative", zIndex:5 },
  emptyState: { display:"flex", flexDirection:"column", alignItems:"center", justifyContent:"center", gap:14, padding:"60px 20px", textAlign:"center" },
  emptyTitle: { fontFamily:"'Playfair Display',serif", fontSize:32, fontWeight:900, color:"var(--text)", letterSpacing:"-0.02em" },
  chip: { fontFamily:"'DM Sans',sans-serif", fontSize:12, fontWeight:500, padding:"8px 18px", border:"1.5px solid rgba(232,53,74,0.3)", borderRadius:24, color:"#E8354A", background:"rgba(232,53,74,0.04)", display:"inline-flex", alignItems:"center" },
  msgWrapper: { display:"flex", flexDirection:"column", gap:4 },
  userBubble: { background:"var(--surface)", border:"1px solid var(--border)", borderRadius:"18px 18px 4px 18px", padding:"14px 18px", maxWidth:"70%", boxShadow:"0 2px 12px rgba(0,0,0,0.06)" },
  modeTag: { fontSize:10, padding:"2px 10px", borderRadius:10, fontWeight:700, color:"#fff", fontFamily:"'DM Sans',sans-serif", letterSpacing:"0.04em" },
  platformTag: { fontSize:10, padding:"2px 10px", borderRadius:10, background:"rgba(0,0,0,0.05)", color:"#aaa", fontFamily:"'DM Sans',sans-serif" },
  assistantRow: { display:"flex", gap:14, alignItems:"flex-start" },
  assistantAvatar: { width:36, height:36, borderRadius:"50%", flexShrink:0, display:"flex", alignItems:"center", justifyContent:"center", fontSize:14, color:"#fff", boxShadow:"0 4px 14px rgba(0,0,0,0.15)" },
  assistantContent: { display:"flex", flexDirection:"column", gap:8, flex:1 },
  assistantText: { fontFamily:"'DM Sans',sans-serif", fontSize:13, color:"var(--text2)", lineHeight:1.85, whiteSpace:"pre-wrap", background:"var(--surface)", border:"1px solid var(--border)", borderRadius:"4px 18px 18px 18px", padding:"18px 22px", boxShadow:"0 2px 16px rgba(0,0,0,0.05)" },
  copyBtn: { alignSelf:"flex-start", background:"transparent", border:"none", color:"#ccc", fontFamily:"'DM Sans',sans-serif", fontSize:11, fontWeight:500, padding:"4px 0", letterSpacing:"0.06em" },
  analysisCard: { background:"var(--surface2)", border:"1px solid rgba(43,181,174,0.2)", borderRadius:14, padding:"20px 22px", display:"flex", flexDirection:"column", gap:14, animation:"slideUp 0.4s cubic-bezier(0.22,1,0.36,1)" },
  analysisSubLabel: { fontFamily:"'DM Sans',sans-serif", fontSize:10, fontWeight:700, color:"#aaa", letterSpacing:"0.12em", textTransform:"uppercase", marginBottom:6 },
  analysisBullet: { fontFamily:"'DM Sans',sans-serif", fontSize:12, color:"var(--text2)", lineHeight:1.7 },
  analysisOptimized: { fontFamily:"'DM Sans',sans-serif", fontSize:13, color:"var(--text)", lineHeight:1.85, whiteSpace:"pre-wrap", background:"var(--surface)", border:"1px solid rgba(43,181,174,0.25)", borderRadius:10, padding:"14px 16px" },
  inputArea: { borderTop:"1px solid var(--border)", background:"var(--glass)", backdropFilter:"blur(20px)", padding:"18px 28px 22px", position:"sticky", bottom:0, zIndex:20 },
  inputWrapper: { maxWidth:900, margin:"0 auto", display:"flex", gap:12, alignItems:"flex-end" },
  textarea: { flex:1, background:"var(--surface)", border:"1.5px solid var(--border)", borderRadius:14, padding:"12px 18px", fontSize:13, fontFamily:"'DM Sans',sans-serif", color:"var(--text)", resize:"none", lineHeight:1.7, transition:"all 0.2s ease", boxShadow:"0 2px 8px rgba(0,0,0,0.04)" },
  sendBtn: { width:52, height:52, border:"none", borderRadius:14, fontSize:20, fontWeight:700, display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0, boxShadow:"0 4px 16px rgba(0,0,0,0.1)" },
};
